# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 15:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.FloatField()),
                ('old_price', models.FloatField()),
                ('url', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribe', models.BooleanField(default=False)),
                ('reason', models.CharField(blank=True, max_length=225, null=True)),
                ('notification_interval', models.CharField(choices=[('ALWAYS', 'ALWAYS'), ('ALL_TIME_LOW', 'ALL_TIME_LOW'), ('MORE_THAN_10', 'MORE_THAN_10')], default='', max_length=25)),
                ('product', models.ManyToManyField(blank=True, null=True, to='treeboapp.Product')),
                ('user', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
