# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 09:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('treeboapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribe', models.BooleanField(default='subscribe')),
                ('reason', models.CharField(max_length=225)),
                ('notification_interval', models.CharField(choices=[('ALWAYS', 'ALWAYS'), ('ALL_TIME_LOW', 'ALL_TIME_LOW'), ('MORE_THAN_10', 'MORE_THAN_10')], max_length=25)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='subscription',
            field=models.ManyToManyField(to='treeboapp.UserSubscription'),
        ),
    ]
