# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treeboapp', '0003_auto_20161118_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='notification_interval',
            field=models.CharField(choices=[('ALWAYS', 'ALWAYS'), ('ALL_TIME_LOW', 'ALL_TIME_LOW'), ('MORE_THAN_10', 'MORE_THAN_10')], default='', max_length=25),
        ),
    ]
