# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treeboapp', '0004_auto_20161118_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='product',
            field=models.ManyToManyField(blank=True, null=True, to='treeboapp.Product'),
        ),
    ]
